// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rob-bot/DepthAtmosphere.tsx": () => import("../components/mockups/rob-bot/DepthAtmosphere.tsx"),
  "./components/mockups/rob-bot/PrecisionRefined.tsx": () => import("../components/mockups/rob-bot/PrecisionRefined.tsx")
};
